CREATE TABLE account(
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	
	PRIMARY KEY (id),
	CONSTRAINT fk_account_user
		FOREIGN KEY (user_id) REFERENCES user (id)
);

-- Altera o valor inicial do AUTO_INCREMENT
ALTER TABLE account AUTO_INCREMENT = 1000;